### ISSUE TITLE
bin.equinox.io is Down Again 

### ISSUE THREAD

**Issue by hintecher** [bubenshchykov/ngrok#185]
bin.equinox.io is not working please provide a solution .

**Comment by philnash** [comment]
That is the URL that the various ngrok executables are hosted at. It is a [service for packaging and distributing Go applications](https://equinox.io/) and it is used by the creators of [ngrok (the application and service)](https://ngrok.com/) for distributing the executable.

This project is Node.js wrapper around the ngrok executable, so sadly if the Equinox server is down then there is little we can do to fix that. I would simply advise that you try downloading again, since I'm sure up-time is an important part of Equinox's SLA with their users.
