### ISSUE TITLE
Extremely slow, esspecially with POST requests

### ISSUE THREAD

**Issue by SilverStrings024** [bubenshchykov/ngrok#192]
Hello! I know an issue has been submitted for slowness but there wasn't an answer on how to fix it. I can do some coding on my side if anyone has any ideas on how to speed it up but I was trying to show my testers the website today and static pages took well over 2 full seconds to load and POST requests took literal minutes. I know this isn't a problem with my query times or anything because...again...static pages were even slow. If you can give me any help, it would be appreciated.

I'm in the testing phase of a website I'm developing and need ngrok so I don't have to launch it with a lock on it especially because my client has their domain point to a weebly website, so I can't take that over and keep people out of it, because it not only kills exposure but also destroys any first impressions. I read that you can specify the nearest server but haven't seen any docs or anything on that. Any help would be greatly appreciated and if I can do anything on my end to help, please let me know and I will do my best.

**Comment by Beelucky** [comment]
> One thing to check is "region" option when creating a tunnel - make sure you use the closest one.
> 
> This module is just a node.js wrapper for ngrok binary, I would recommend contacting https://ngrok.com/

I have tested the internet service provider with ngrok, when anyone enters the ngrok address then in the end my bandwidth attracts another connection and it is like making a download for me who runs ngrok and not the client or other people who download it. Let's simplify that again You know when the ngrok program is activated every client or someone else enters the ngrok address so I also download? 

That's normal?

 I hope you make other changes so that those who download only come to the ngrok address on localhost and not those who activate ngrok, so far I have found that peer connections often experience errors, and in my opinion you should eliminate the 7 hour time to outgoing server time up.

Once more, you should make the address exclude feature enabled when ngrok is enabled as in standard input and standard output eg.example; "Ngrok http 80> export> address ngrok to> ngrokname.txt and we can know now what address is stated in note.txt so it will be more powerful and user friendly
