### ISSUE TITLE
Why does Session Status always reconnect? I can't get a link:(

### ISSUE THREAD

**Issue by Cheposik** [bubenshchykov/ngrok#204]
![IMG_20201231_043051.jpg](https://user-images.githubusercontent.com/76786252/103389613-fe27f400-4b20-11eb-99a8-543e495b7af5.jpg)
![IMG_20201231_043710.jpg](https://user-images.githubusercontent.com/76786252/103389784-092f5400-4b22-11eb-8d57-6e8e133f8dd4.jpg)

**Comment by philnash** [comment]
Hey @Cheposik, thanks for coming back in a new issue!

Sadly, this is the repo for the [Node module](https://www.npmjs.com/package/ngrok) that controls the ngrok executable and not ngrok itself. We have no affiliation with the ngrok service or the executable itself. I'd recommend bringing this up with ngrok themselves. You can get in touch with ngrok support by heading to [https://ngrok.com](https://ngrok.com) and clicking on the "Ask a question" box. Or you may be able to contact them through [their Twitter handle: ngrok_](https://twitter.com/ngrok_).

Since there is nothing we can do in this repo, I will close this issue for now. I hope you get it sorted though.
