### ISSUE TITLE
ngrok craches on macos 11.2 on M1 processor

### ISSUE THREAD

**Issue by d2bspzoo** [bubenshchykov/ngrok#207]
Hi,

I found that ngrok implementation in expo (@expo/ngrok) crashes on macOS 11.2 on M1 processor. 
It returns:
Tunnel URL not found (it might not be ready yet), falling back to LAN URL.
Error starting tunnel Starting tunnels timed out.
When I check Console, there is a crash report on that. 
I checked the same project on macOS 11.2 running on Intel processor and everyting works as a charm.

Jakub

**Comment by philnash** [comment]
[`@expo/ngrok` seems to be a separate fork of this project](https://github.com/expo/ngrok). However, the issue is more likely with the [ngrok project](https://ngrok.com/) itself rather than one of the Node.js wrappers. I would recommend heading to [ngrok.com](https://ngrok.com/) and using the "Ask a question" button which sends questions and issues to the ngrok team.

**Comment by d2bspzoo** [comment]
Hi
Thanks for your reply. 

Ngrok works fine by it self on macOS 11.2 on M1 processor. I can establish a tunnel manually for terminal. It looks like @expo/ngrok crashes and indeed it is forked from here :) 

Best regards Jakub

**Comment by philnash** [comment]
You could try installing this project, which is just `npm install ngrok`, to see if it runs on the M1. Maybe it will be able to solve your problem.

**Comment by d2bspzoo** [comment]
I installed ngrok 3.4.0 using yarn. I have the same results i.e. crash, but I am not sure if expo is using 3.4.0 or by default 2.4.3 which is actually @expo/ngrok.

**Comment by philnash** [comment]
Does the ngrok executable, downloaded from [ngrok.com](https://ngrok.com), work for you?

**Comment by d2bspzoo** [comment]
Yes it works (version 2.3.35). I am using it as a kinda workaround of the problem, but it is painful :)

**Comment by philnash** [comment]
Can you share the stack trace of the error when using the `ngrok` project? (Not `@expo/ngrok` as I can’t help with that.)

**Comment by philnash** [comment]
Also, you can pass a `binPath` option to `ngrok.connect` to use a different installation of ngrok.

**Comment by brendo-m** [comment]
I've run into the same issue and have done some poking around.

https://github.com/expo/ngrok/blob/master/packages/ngrok-bin/index.js resolves `ngrok-bin-darwin-x64` but we actually need `ngrok-bin-darwin-arm64`.

When I replace the binary with the right one from ngrok.com it no longer hangs and times out but I get `ngrok is not yet ready to start tunnels`. Haven't determined if this is due to my environment yet but at minimum looks like we need a new binary and an update to the logic above

**Comment by brendo-m** [comment]
Problem is https://github.com/bubenshchykov/ngrok/issues/148

I confirmed it works after hacking in a check for 503 error code

**Comment by philnash** [comment]
Hey @d2bspzoo and @brendo-m, you're both talking about `@expo/ngrok` which is a fork of this project that was last updated a couple of years ago. This [project does test for 503s](https://github.com/bubenshchykov/ngrok/blob/1963e3a5e592df98ecd21404aec758055d444774/src/utils.js#L39), for example.

This issue is already closed, since I can't fix expo/ngrok from here. I suggest you take the issue up with [expo/ngrok](https://github.com/expo/ngrok).

**Comment by brendo-m** [comment]
Ah my bad, I thought I was commenting on the right issue. Thanks!

**Comment by philnash** [comment]
@brendo-m No problems! Just pointing out that I couldn't help here. Hope you get things sorted!

**Comment by tabvn** [comment]
i got same issue on apple macbook pro chip silicon.

anyone can recommend quick hack to fix ?

**Comment by philnash** [comment]
@tabvn Are you using the latest version of this project? Or @expo/ngrok, like others in this thread?

**Comment by tabvn** [comment]
@philnash yes i am, i 'm using latest version from Expo, i just bought apple m1 two days ago.

**Comment by philnash** [comment]
@tabvn As discussed above, the [Expo fork of this library](https://github.com/expo/ngrok) is a fork of this project. It also hasn't been updated for about 3 years. This project does handle Apple M1 machines, as well as the 503 errors reported earlier too.

You have two things you can do. Either change your project to use this ngrok (available through `npm install ngrok` instead of `@expo/ngrok`), or take up the issue with Expo and get them to update their fork. We can't fix the issues with `@expo/ngrok` in this project though.

**Comment by tabvn** [comment]
@philnash  thank you. That mean i should wait for Expo team get this fixed.

**Comment by philnash** [comment]
@tabvn Yes, if you can contact them and raise the issue with them, then they will have to fix it. It appears that they have moved their ngrok implementation into the [expo-cli project](https://github.com/expo/expo-cli/), and that you might be able to raise an issue there. Good luck getting it fixed.

**Comment by tabvn** [comment]
@philnash thanks for your contributing (y)
