### ISSUE TITLE
UDP?

### ISSUE THREAD

**Issue by TheBotlyNoob** [bubenshchykov/ngrok#219]
Or some other program that has a javascipt api and UDP?

**Comment by philnash** [comment]
ngrok does not support UDP, that I know of.

Other people want this feature too. Here are some links that might help with suggestions:

- https://www.reddit.com/r/networking/comments/ji000n/ngrok_udp_alternative/
- https://github.com/inconshreveable/ngrok/issues/422
- https://github.com/inconshreveable/ngrok/issues/26

I'll close this issue as it's not something that can be fixed in this project. Hope you find something!
