### ISSUE TITLE
ngrok laggy and crashes

### ISSUE THREAD

**Issue by MrRandom92** [bubenshchykov/ngrok#224]
Scaling Command Prompt after running `ngrok http 8080` with the top left corner causes cmd/ngrok to freeze/close.
Inspecting requests with the real-time web UI is laggy and causes the page to freeze.

**ngrok version:** 2.3.40 x64
**OS:** Windows 10 x64

The issue doesn't seem to be present in older versions such as v2.0.21.

_I understand this may be unrelated to the node wrapper._

**Comment by philnash** [comment]
If you are running ngrok via the command line then the issue does not lie with the Node wrapper here.

I suggest you try using the "Ask a question" widget on ngrok.com, asking in [the ngrok forum](https://discuss.ngrok.com/) or asking about it [on Twitter](https://twitter.com/ngrok_).

**Comment by MrRandom92** [comment]
I just thought you should know about the issue in case others conflate it with the wrapper, as the Global install section of the readme includes the command line example ``ngrok http 8080``. Thanks anyway.

**Comment by philnash** [comment]
@MrRandom92 Ah, I did wonder why you raised it and acknowledged that it is unrelated! Plenty of people raise issues with this repo that are the responsibility of the main ngrok executable. The README includes that command line example because installing this package globally will put the downloaded ngrok executable on the `PATH` and allow you to run it, but when you do, you are using the ngrok executable directly.

If others bring the issue up, I'll direct them to this issue.

Thanks!
