### ISSUE TITLE
Nodejs installation not working

### ISSUE THREAD

**Issue by PSYASHAS** [bubenshchykov/ngrok#241]
npm install ngrok 

This is not working
Pls say solution

**Comment by philnash** [comment]
What isn't working about it? Do you get an error? Please share that error.

**Comment by philnash** [comment]
Hey @PSYASHAS, I've not heard back from you. In order to investigate this any further I need more details. I'm going to close this issue for now, but if you can share any more details, like what you have done, what you expected to happen and what actually happened, then please re-open the issue and I can take a look.
