### ISSUE TITLE
Equinox io Certificate Expired

### ISSUE THREAD

**Issue by wluisi** [bubenshchykov/ngrok#250]
I'm getting the following error on my CI platform that uses a package that depends on ngrok:

```
ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
ngrok - error downloading binary { Error: certificate has expired
```

Tested with curl as well and the certificate appears to have expired
```
curl https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
curl: (60) SSL certificate problem: certificate has expired
```

**Comment by wluisi** [comment]
Seems like Equinox io shut down this morning? https://equinox.io/ -- are there plans to upgrade ngrok to use another cdn provider?

**Comment by philnash** [comment]
I got in touch with the ngrok team and they told me that they will be continuing to publish to equinox in some sort of shut down deal. Meanwhile, this repo will have to wait and see what happens.

**Comment by philnash** [comment]
I wrote to ngrok again myself to see what was going on. Apparently any certificate issues have been down to the Let's Encrypt root expiring on September 30th (and it was coincidence that this was the date Equinox was due to close down). I think this is a good, in depth [explanation of what happened with Let's Encrypt](https://scotthelme.co.uk/lets-encrypt-old-root-expiration/) and why it might have affected you and what you can do to ensure your system trusts certificates from Let's Encrypt, and thus Equinox, again.

To reiterate: Equinox is not shutting down, the ngrok team are continuing to serve ngrok binaries from Equinox and you should be able to download them successfully from there. If you can't, it is likely an SSL issue that you can solve by [following these instructions](https://scotthelme.co.uk/lets-encrypt-old-root-expiration/#affected-clients).

Let me know if that helps and if you are able to download ngrok binaries again.

**Comment by philnash** [comment]
Is anyone still having problems with this, or can I close this out?

**Comment by philnash** [comment]
I've not received any further reports of equinox certificate issues, so I'm going to close this issue. If you do find this is an issue, please check with the [ngrok team](https://ngrok.com) first before re-opening this issue, this repo is not part of the code ngrok product, nor the equinox product, and has no control over either of them.
